import streamlit as st
import requests
import datetime

# from exception.exceptions import TradingBotException
import sys

import streamlit as st
import datetime
import os

# 🔹 Travel Plan Generator (dummy logic for now)
def generate_travel_plan(user_input):
    if "Goa" in user_input:
        return """
        ✈️ **Travel Plan for Goa (5 Days)**

        **Day 1:** Arrival in Goa, beachside relaxation at Baga Beach  
        **Day 2:** Visit Old Goa Churches, spice plantations  
        **Day 3:** Water sports at Calangute & Anjuna beach  
        **Day 4:** Explore Dudhsagar Waterfalls & wildlife sanctuary  
        **Day 5:** Shopping at Mapusa market, departure  

        🌤️ Weather: Warm & sunny  
        💰 Approx Budget: $500 - $700
        """
    else:
        return f"Here’s a sample travel plan for: {user_input}\n\n(Detailed AI logic can go here!)"

# 🔹 Streamlit UI
st.set_page_config(
    page_title="🌍 Travel Planner Agentic Application",
    page_icon="🌍",
    layout="centered",
    initial_sidebar_state="expanded",
)

st.title("🌍 Travel Planner Agentic Application")

# Chat input form
st.header("How can I help you in planning a trip? Let me know where do you want to visit.")

with st.form(key="query_form", clear_on_submit=True):
    user_input = st.text_input("User Input", placeholder="e.g. Plan a trip to Goa for 5 days")
    submit_button = st.form_submit_button("Send")

if submit_button and user_input.strip():
    with st.spinner("Bot is thinking..."):
        answer = generate_travel_plan(user_input)

        markdown_content = f"""# 🌍 AI Travel Plan

        # **Generated:** {datetime.datetime.now().strftime('%Y-%m-%d at %H:%M')}  
        # **Created by:** Aamir Rashid 

        ---

        {answer}

        ---

        *This travel plan was generated by AI. Please verify all information, especially prices, operating hours, and travel requirements before your trip.*
        """
        st.markdown(markdown_content)


import os

GOOGLE_API_KEY = st.secrets.get("GOOGLE_API_KEY", os.getenv("GOOGLE_API_KEY"))
TAVILAY_API_KEY = st.secrets.get("TAVILAY_API_KEY", os.getenv("TAVILAY_API_KEY"))
FOURSQUARE_API_KEY = st.secrets.get("FOURSQUARE_API_KEY", os.getenv("FOURSQUARE_API_KEY"))
OPENWEATHERMAP_API_KEY = st.secrets.get("OPENWEATHERMAP_API_KEY", os.getenv("OPENWEATHERMAP_API_KEY"))
EXCHANGE_RATE_API_KEY = st.secrets.get("EXCHANGE_RATE_API_KEY", os.getenv("EXCHANGE_RATE_API_KEY"))





